# Nós utilizados nos Métodos de Amplitude, Profundidade Limitada, Profundidade, Aprofundamento Interativo, Bidirecional,

nos = ["Cruzeiro",
       "Queluz",
       "Resende",
       "Lorena",
       "Cachoeira Paulista",
       "Lavrinhas",
       "Piquete",
       "Areias",
       "Guaratingueta",
       "Itajuba",
       "Sao Lourenco",
       "Itanhandu",
       "Itatiaia",
       "Taubate",
       "Campos do Jordao",
       "Pindamonhangaba",
       "Aparecida",
       "Roseira",
       "Caçapava",
       "Passa Quatro",
       "Itamonte",
       "Pouso Alto"
       ]